### ISSUE TITLE
beautifying readme

### ISSUE THREAD

**Issue by himanshu007-creator** [shatakshisingh24/Medvice#11]
i would like to work on this issue as part of DWOC .

to-do list:-
- animated Banner for readme
- using emojis

Please add <code> DWOC</code> and <code>level 1</code> tags to labels field

**Comment by shatakshisingh24** [comment]
Great,Go ahead!

**Comment by himanshu007-creator** [comment]
Job done . https://github.com/shatakshisingh24/Medvice/pull/13

**Comment by shatakshisingh24** [comment]
Thanks
