### ISSUE TITLE
Starting the frontend work for the web app

### ISSUE THREAD

**Issue by shubhraagarwal** [shatakshisingh24/Medvice#19]
I would like to start working on the frontend of this project by creating a seperate folder called "frontend" and making contributions to it. If you could tell me your requirements about the page, that'd be great.

**Comment by shatakshisingh24** [comment]
That will be great. Please go ahead.

Requirements:
1. Frontpage/ welcome page.
2. Taking input values for diabetes detection. Foe the input values you may refer to dataset

**Comment by shubhraagarwal** [comment]
What will be the tech stack for the frontend? Plain html css js or reactjs?

And the input portion, does it need to be in the homepage itself or go I create a separate page for it?

**Comment by shubhraagarwal** [comment]
Is the project active?

**Comment by shubhraagarwal** [comment]
Do you mind replying to this issue?

**Comment by shatakshisingh24** [comment]
Hi! Apologies for the delayed response.
Html Css will do.
