### ISSUE TITLE
PR TEMPLATE 

### ISSUE THREAD

**Issue by akrish4** [shatakshisingh24/Medvice#4]
I would like to add a pr template which will give a template and users need to fill it inorder to open a pr and maintainer will get better understanding of the pr with images

Kindly do assign me

**Comment by shatakshisingh24** [comment]
Great! Please go ahead

**Comment by akrish4** [comment]
Thank you 
Kindly add the `DWOC` and  `Level` label

**Comment by shatakshisingh24** [comment]
Done

**Comment by akrish4** [comment]
Kindly add  `Level` label and also assign me
