### ISSUE TITLE
Add Contributors Table in README.md

### ISSUE THREAD

**Issue by samir-0711** [shatakshisingh24/Medvice#5]
Like this
![image](https://user-images.githubusercontent.com/68433936/104811853-6dd9f680-5824-11eb-9353-135ca443c420.png)

**Comment by samir-0711** [comment]
I would like to work on this.

**Comment by shatakshisingh24** [comment]
Great,Go aheah!

**Comment by shatakshisingh24** [comment]
Hey, thanks for adding it. Could you please add other contributors too.
