### ISSUE TITLE
BACKEND DESIGN 

### ISSUE THREAD

**Issue by Novartus** [shatakshisingh24/Medvice#6]
I can work on the back-end development of this project using Node.JS, Express.JS and PostgresSQL as Database.

Let me know if you are interested

Kindly do assign me
Kindly do add the DWOC and Level label

**Comment by shatakshisingh24** [comment]
Sure

**Comment by Novartus** [comment]
Okay, On it, working on the base of the back end ! but can you please add a level to this issue  @shatakshisingh24 ? That would be really helpful.

**Comment by shatakshisingh24** [comment]
Sure I will add level lable. Once we'll train the models for the diabetes dataset you can add those fields in the dataset.

**Comment by Novartus** [comment]
Okay, can you provide me column names or rough database ? Because I will need to create tables according to that in DB.

**Comment by shatakshisingh24** [comment]
Yeah, you can find the diabetes dataset in the folder named diabetes. It is a excel worksheet. Dataset is in the sheet named Diabetes_Classification.

**Comment by Novartus** [comment]
Sorry accidentally pressed closed button.😅

**Comment by shatakshisingh24** [comment]
No prob:)
